name: secubase
favicon: null
layout_spectrum: 0.11494861566461623
typography_spectrum: 0.5362126897089183
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8818158896174282
  lightness: 0.09922965802252293
  saturation: 0.32174603594467044
  rhythmicContrast: 0.8474655458703637
purpose: []
